version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_todos
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .db/.data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
